name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Linter
        run: pnpm lint

      - name: E2E test
        run: pnpm test

      - name: 部署测试报告到服务器
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: coverage/
          target: ~/Projects/.utils_coverage_temp/
          rm: true
          strip_components: 1

      - name: 执行远程脚本命令
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            mkdir -p ~/Projects/utils-coverage
            rm -rf ~/Projects/utils-coverage/*
            cp -rf ~/Projects/.utils_coverage_temp/*  ~/Projects/utils-coverage/
            rm -rf ~/Projects/.utils_coverage_temp
